## BCH

In [1]:
import bchlib

ModuleNotFoundError: No module named 'bchlib'

## LDPC

In [2]:
import numpy as np
from pyldpc import make_ldpc, encode, decode, get_message

In [8]:
n = 15
d_v = 4
d_c = 5
snr = 20
H, G = make_ldpc(n, d_v, d_c, systematic=True, sparse=True)
k = G.shape[1]
#v = np.random.randint(2, size=k)
v = np.array([0, 1, 1, 1, 0 ,1])
y = encode(G, v, snr)
d = decode(H, y, snr)
x = get_message(G, d)
assert abs(x - v).sum() == 0

In [9]:
y

array([ 1.01612841, -1.00494006, -0.99136653, -1.13339911,  1.07048122,
       -1.03511737, -1.14462632, -0.80779379, -0.9027983 ,  0.88041193,
       -1.08414492, -1.03195437, -1.13496657, -0.90104554, -0.89454301])

In [10]:
d

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [11]:
v

array([0, 1, 1, 1, 0, 1])

In [12]:
x

array([0, 1, 1, 1, 0, 1])